#!/usr/bin/env python3
"""
Azentio Hackathon: Empirical Evaluation - Base SLM vs Fine-Tuned LoRA SLM
========================================================================
Evaluates both Base Qwen2.5-1.5B-Instruct and Fine-Tuned LoRA model on the
SAME held-out test set (data/test_weak_labels.jsonl).

CRITICAL NOTICE:
  The ground truth labels in data/test_weak_labels.jsonl are WEAK LABELS
  generated by domain heuristics. The metrics computed below (Accuracy,
  Precision, Recall, F1) evaluate AGREEMENT WITH WEAK LABELS and structured
  JSON adherence, rather than real-world verified fraud accuracy.
"""

import argparse
import json
import re
import sys
import time
from pathlib import Path
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate Base vs LoRA Qwen2.5-1.5B")
    parser.add_argument("--base-model", type=str, default="Qwen/Qwen2.5-1.5B-Instruct")
    parser.add_argument("--adapter-dir", type=str, default="models/fraud-sentinel-lora")
    parser.add_argument("--test-data", type=str, default="data/test_weak_labels.jsonl")
    parser.add_argument("--limit", type=int, default=150, help="Number of test samples to evaluate (default: 150)")
    parser.add_argument("--output-json", type=str, default="evaluation_comparison.json")
    return parser.parse_args()

def extract_json_prediction(raw_text: str):
    """Robustly extract JSON risk profile from model generation."""
    cleaned = raw_text.strip()
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    
    # Try direct parse
    try:
        data = json.loads(cleaned)
        if isinstance(data, dict) and "is_fraud" in data:
            is_f = data["is_fraud"]
            if isinstance(is_f, str):
                is_f = is_f.lower() in ("true", "yes", "1")
            return bool(is_f), True, data
    except Exception:
        pass
        
    # Regex extract
    m = re.search(r"\{[\s\S]*?\}", cleaned)
    if m:
        try:
            data = json.loads(m.group())
            if isinstance(data, dict) and "is_fraud" in data:
                is_f = data["is_fraud"]
                if isinstance(is_f, str):
                    is_f = is_f.lower() in ("true", "yes", "1")
                return bool(is_f), True, data
        except Exception:
            pass

    return None, False, None

def evaluate_model(model, tokenizer, test_samples, model_name: str):
    print(f"\nEvaluating: {model_name} on {len(test_samples)} held-out samples...")
    t0 = time.time()
    
    tp = 0
    fp = 0
    tn = 0
    fn = 0
    valid_json_count = 0
    predictions = []

    for i, sample in enumerate(test_samples, start=1):
        messages = sample["messages"]
        prompt_msgs = messages[:2]  # system + user
        target = json.loads(messages[2]["content"])
        true_fraud = bool(target["is_fraud"])

        # Format input using ChatML template
        chat_text = tokenizer.apply_chat_template(prompt_msgs, tokenize=False, add_generation_prompt=True)
        inputs = tokenizer(chat_text, return_tensors="pt")

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=90,
                temperature=0.01,
                do_sample=False,
                pad_token_id=tokenizer.pad_token_id,
            )

        gen_text = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
        pred_fraud, is_valid, json_data = extract_json_prediction(gen_text)

        if is_valid:
            valid_json_count += 1
            if pred_fraud and true_fraud:
                tp += 1
            elif pred_fraud and not true_fraud:
                fp += 1
            elif not pred_fraud and not true_fraud:
                tn += 1
            elif not pred_fraud and true_fraud:
                fn += 1
        else:
            # Invalid JSON counts as error (treated as negative)
            if true_fraud:
                fn += 1
            else:
                tn += 1

        predictions.append({
            "sample_index": i,
            "true_fraud": true_fraud,
            "pred_fraud": pred_fraud,
            "is_valid_json": is_valid,
            "raw_output": gen_text.strip(),
        })

        if i % 25 == 0 or i == len(test_samples):
            print(f"  [{i}/{len(test_samples)}] processed in {time.time() - t0:.1f}s | Valid JSON: {valid_json_count}/{i}")

    total_valid = tp + fp + tn + fn
    accuracy = (tp + tn) / total_valid if total_valid > 0 else 0.0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    json_rate = valid_json_count / len(test_samples) if test_samples else 0.0

    metrics = {
        "model_name": model_name,
        "total_samples": len(test_samples),
        "valid_json_count": valid_json_count,
        "json_validity_rate": round(json_rate, 4),
        "tp": tp,
        "fp": fp,
        "tn": tn,
        "fn": fn,
        "confusion_matrix": [[tn, fp], [fn, tp]],
        "accuracy": round(accuracy, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4),
        "total_eval_time_sec": round(time.time() - t0, 2),
    }
    return metrics, predictions

def main():
    args = parse_args()
    base_dir = Path(__file__).resolve().parent
    test_path = base_dir / args.test_data
    adapter_path = base_dir / args.adapter_dir

    if not test_path.exists():
        raise FileNotFoundError(f"Test data not found: {test_path}")

    # Load test samples
    test_samples = []
    with open(test_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                test_samples.append(json.loads(line))

    if args.limit and args.limit < len(test_samples):
        test_samples = test_samples[:args.limit]

    print("=" * 70)
    print("📊 Azentio Empirical Evaluation: Base SLM vs Fine-Tuned LoRA")
    print("=" * 70)
    print(f"Test Set:      {test_path} ({len(test_samples)} samples)")
    print(f"Base Model:    {args.base_model}")
    print(f"LoRA Adapter:  {adapter_path}")
    print("⚠️  Metric Context: Measuring agreement against heuristic WEAK LABELS")
    print("=" * 70)

    # 1. Load Tokenizer & Base Model
    print("\nLoading tokenizer and Base Model...")
    tokenizer = AutoTokenizer.from_pretrained(args.base_model, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    base_model = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        torch_dtype=torch.float32,
        low_cpu_mem_usage=True,
        trust_remote_code=True,
    )
    base_model.eval()

    # Evaluate Base Model
    base_metrics, base_preds = evaluate_model(base_model, tokenizer, test_samples, "Base Qwen2.5-1.5B-Instruct")

    # 2. Attach LoRA Adapter
    print(f"\nAttaching LoRA Adapter from {adapter_path}...")
    lora_model = PeftModel.from_pretrained(base_model, str(adapter_path))
    lora_model.eval()

    # Evaluate Fine-Tuned LoRA Model
    lora_metrics, lora_preds = evaluate_model(lora_model, tokenizer, test_samples, "Fine-Tuned Qwen2.5-1.5B + LoRA")

    # Print Comparison Table
    print("\n" + "=" * 70)
    print("🏆 COMPARATIVE EVALUATION RESULTS (Held-Out Test Set)")
    print("=" * 70)
    print(f"{'Metric':<25} {'Base Qwen2.5-1.5B':<22} {'Fine-Tuned LoRA':<20}")
    print("-" * 70)
    print(f"{'JSON Validity Rate':<25} {base_metrics['json_validity_rate']*100:.1f}%{'':<16} {lora_metrics['json_validity_rate']*100:.1f}%")
    print(f"{'Accuracy (Weak Label)':<25} {base_metrics['accuracy']*100:.1f}%{'':<16} {lora_metrics['accuracy']*100:.1f}%")
    print(f"{'Precision (Weak Label)':<25} {base_metrics['precision']:.4f}{'':<16} {lora_metrics['precision']:.4f}")
    print(f"{'Recall (Weak Label)':<25} {base_metrics['recall']:.4f}{'':<16} {lora_metrics['recall']:.4f}")
    print(f"{'F1-Score (Weak Label)':<25} {base_metrics['f1']:.4f}{'':<16} {lora_metrics['f1']:.4f}")
    print(f"{'Confusion Matrix':<25} {str(base_metrics['confusion_matrix']):<22} {str(lora_metrics['confusion_matrix']):<20}")
    print("=" * 70)

    # Save to JSON
    out_obj = {
        "dataset_notice": "Evaluated against heuristic WEAK LABELS on held-out test split (seed=42).",
        "test_samples_evaluated": len(test_samples),
        "base_model": base_metrics,
        "lora_model": lora_metrics,
    }
    with open(base_dir / args.output_json, "w", encoding="utf-8") as f:
        json.dump(out_obj, f, indent=2)
    print(f"\nDetailed evaluation metrics exported to {args.output_json}")

if __name__ == "__main__":
    main()
